Europe/Models/Student.cs
using DAL.Services;
using Europe.Mapper;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

namespace Europe.Models
{
	public class Student
	{
		// TABLE STUDENT
		// ------------------------------------------

		[HiddenInput(DisplayValue = false)]
		public int Id { get; set; }

		[HiddenInput(DisplayValue = false)]
		public int UserId { get; set; }

		public int ImgId { get; set; }

        public int RoleTpe
        {
            get { return 2; }
        }

		// TABLE USER
		// ------------------------------------------

		private DAL.Data.User _User;
		public DAL.Data.User User
		{
			get
			{
				if (_User == null)
				{
					UserService userService = new UserService();
					_User = userService.Get(UserId);
				}
				return _User;
			}
		}

		// TABLE STUDENTCOURSE
		// ------------------------------------------

		private IEnumerable<StudentCourse> _StudentCourses;
		public IEnumerable<StudentCourse> StudentCourses
		{
			get
			{
				if (_StudentCourses == null)
				{
					CourseService courseService = new CourseService();
					_StudentCourses = courseService.GetCoursesByStudentId(Id).Select(c => c.ToStudentCourseModel()).ToList();
				}
				return _StudentCourses;
			}
		}

		public int Points; 

		public int GetPointsByCourse(int courseId)
		{
			// On récupère le studentCourse d'un étudiant
			CourseService serv = new CourseService();
			StudentCourse studentCourse = serv.GetByStudentIdAndCourseId(Id, courseId).ToStudentCourseModel();
						
			Points = studentCourse.Points;
			return Points;
		}

		private int _TotaPoints;
		public int TotalPoints
		{			
			get
			{
				if (_StudentCourses != null)
				{
					List<StudentCourse> list = _StudentCourses.ToList();

					for (int i = 0; i < list.Count(); i++)
					{
						_TotaPoints += list[i].Points;
					}
					return _TotaPoints;
				}
				else
				{
					_TotaPoints = -1;
					return _TotaPoints;
				}				
			}
		}

		// TABLE CERTIFICATE
		// ------------------------------------------

		[Display(Name = "Certificats obtenus")]
		public IEnumerable<Certificate> Certificates { get; set; }

		// TABLE STUDENTBADGE
		// ------------------------------------------

		[Display(Name = "Badges obtenus")]
		private IEnumerable<StudentBadge> _StudentBadges;
		public IEnumerable<StudentBadge> StudentBadges
		{
			get
			{
				if (_StudentBadges == null)
				{
					StudentBadgeService studentBadgeService = new StudentBadgeService();
					_StudentBadges = studentBadgeService.GetByStudentId(Id).Select(c => c.ToStudentBadgeModel()).ToList();					
				}
				return _StudentBadges;
			}
		}

		public string CssClass { get; set; }
	}
}

Europe/Models/StudentForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Europe.Models
{
	public class StudentForm
	{

		[HiddenInput(DisplayValue = false)]
		public int RoleType
		{
			get	{ return 2; }
		}

		[HiddenInput(DisplayValue = false)]
		public int ImgId { get; set; }

		[Required(ErrorMessage = "N'oublie pas ton pseudo")]
		[Display(Name = "Nom")]
		public string Name { get; set; }

		[DataType(DataType.EmailAddress)]
        [Remote("IsEmailFree", "Account", HttpMethod = "POST", ErrorMessage = "L'adresse e-mail est déjà existante")]
        [Required(ErrorMessage = "N'oublie pas ton adresse e-mail")]
		[Display(Name = "E-mail")]
		public string Email { get; set; }

		[DataType(DataType.EmailAddress)]
		[Required(ErrorMessage = "Confirme ton adresse e-mail")]
		[Display(Name = "Confirmation de l'E-mail")]
		[System.ComponentModel.DataAnnotations.Compare(nameof(Email), ErrorMessage = "La confirmation de l'e-mail est vide ou ne correspond pas")]
		public string ConfirmEmail { get; set; }

		[DataType(DataType.Password)]
		[Required(ErrorMessage = "Renseigne ton mot de passe")]
		[Display(Name = "Mot de passe")]
		public string Pwd { get; set; }

		[DataType(DataType.Password)]
		[Required(ErrorMessage = "Confirme ton mot de passe")]
		[Display(Name = "Confirmation du mot de passe")]
		[System.ComponentModel.DataAnnotations.Compare(nameof(Pwd), ErrorMessage = "Le mot de passe est vide ou ne correspond pas")]
		public string ConfirmPwd { get; set; }
	}
}

Europe/Controllers/ImgController.cs
using DAL.Services;
using Europe.Mapper;
using Europe.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Europe.Controllers
{
    public class ImgController : Controller
    {
		// GET : Img by ID
		public ActionResult Get(int id)
		{
			ImgService imgService = new ImgService();
			Img img = new Img();
			img = imgService.Get(id).ToModelImg();
			byte[] imgByteArray = img.Data;
			string formatWithoutPoint = img.Format.Substring(1);
			string arg = "image/" + formatWithoutPoint;
			return File(imgByteArray, arg);
		}

		// Récupération de toutes les images : gestion admin des images
		public ActionResult GetAll()
		{
			ImgService imgService = new ImgService();
			List<Img> imgs = imgService.Get().Select(c => c.ToModelImg()).ToList();
			return PartialView("_ImgAll", imgs);
		}

		// Affichage de l'avatar via vue partielle
		public ActionResult DisplayImg(int imgId)
		{
			ImgService imgService = new ImgService();
			Img img = new Img();
			img = imgService.Get(imgId).ToModelImg();
			return PartialView("_Img", img);
		}
		
		// Affichage de l'image via Json : gestion admin des images
		public JsonResult GetImgJson(int imgId)
		{
			ImgService imgService = new ImgService();
			Img img = new Img();
			img = imgService.Get(imgId).ToModelImg();
			return Json(img, JsonRequestBehavior.AllowGet);
		}

		// Suppression de l'avatar dans l'édition du profil utilisateur
		public ActionResult DeleteAvatar(int imgId, int userId)
		{
			// Suppression de l'image de l'utilisateur -- côté DB un set default suit le delete
			ImgService imgService = new ImgService();
			imgService.Delete(imgId);

			// Récupération du type d'utilisateur : l'image par défaut correspond au RoleType
			UserService s = new UserService();
			int roleType = s.Get(userId).RoleType;

			//// Renvoyer l'image par défaut à la vue partielle
			Img img = new Img();
			img = imgService.Get(roleType).ToModelImg();
			//return PartialView("_TestImg", img);
			return Json(img, JsonRequestBehavior.AllowGet);
		}
	}
}

Europe/Controllers/StudentController.cs
using DAL.Services;
using Europe.Mapper;
using Europe.Models;
using Europe.Utils;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Europe.Controllers
{
    [AuthRequired]
    public class StudentController : Controller
    {
		[HttpGet]
		[AllowAnonymous]
		public ActionResult Get(int id)
		{
            StudentService studentService = new StudentService();
			Student student = new Student();
			student = studentService.Get(id).ToStudentModel();

			if (student.StudentCourses != null)
			{
				ViewBag.StudentPoint = student.StudentCourses.Sum(c => c.Points);
			}
			else
			{
				ViewBag.StudentPoint = 0;
			}

			// ViewBags
			ViewBag.Date = "Actif depuis : ";
			//ViewBag.ImgSrc = imageDataURL;
			return View(student);
		}

		[HttpGet]
		public ActionResult Update(int id)
		{
			// Le CTO du StudentUpdateForm instancie un student et récupère ses data en les insérant dans le form
			StudentUpdateForm form = new StudentUpdateForm(id);
            //ChangePwd changePwd = new ChangePwd();
            form.IsFlagSet = false;
            return View(form);
		}

		[HttpPost]
		public ActionResult Update(StudentUpdateForm form)
		{
			if (!ModelState.IsValid)
			{
				form.IsFlagSet = true;
				return View(form);
			}
			else
			{
				// Si un fichier est chargé par l'utilisateur on traite l'image...

				if (form.File != null && form.File.ContentType.Contains("image"))
				{
					string[] formats = new string[] { ".jpg", ".png", ".gif", ".jpeg" };

					if (formats.Any(item => form.File.FileName.EndsWith(item, StringComparison.OrdinalIgnoreCase)))
					{
						// Méta données de l'image 

						string alt = "avatar de " + form.Name + ", étudiant de Europe&Un";
						string imgFormat = Path.GetExtension(form.File.FileName);
						string name = Guid.NewGuid().ToString();

						// Encodage de l'image en byte array

						byte[] data;
						using (Stream inputStream = form.File.InputStream)
						{
							MemoryStream memoryStream = inputStream as MemoryStream;
							if (memoryStream == null)
							{
								memoryStream = new MemoryStream();
								inputStream.CopyTo(memoryStream);
							}
							data = memoryStream.ToArray();

							ImgService serv = new ImgService();

							// Si l'utilisateur ajoute son image custom, on l'insère dans la table Img et on update la table Student
							// Sinon s'il update une image custom déjà présente, on update celle-ci au même id

							if (form.ImgId == 2)
							{
								form.ImgId = serv.Insert(new DAL.Data.Img()
								{
									Data = data,
									Format = imgFormat,
									Name = name,
									Size = form.File.ContentLength,
									Alt = alt,
								});
								StudentService studentService = new StudentService();
								studentService.UpdateStudentImgId(new DAL.Data.Student()
								{
									Id = form.Id,
									ImgId = form.ImgId
								});
							}
							else
							{
								serv.Update(new DAL.Data.Img()
								{
									Id = form.ImgId,
									Data = data,
									Format = imgFormat,
									Name = name,
									Size = form.File.ContentLength,
									Alt = alt,
								});
							}
						}
					}
					else
					{
						// avertir l'utilisateur que le format n'est pas adéquant, déjà le faire côté client
						return View(form);
					}
				}
				else
				{
					// Si aucun fichier n'est chargé, il faut vérifier
				}
			}
			UserService userService = new UserService();
			userService.Update(new DAL.Data.User()
			{				
				Name = form.Name,
				Email = form.Email,
				Pwd = form.CurrentPwd,
				Id = form.UserId,
			});
			return RedirectToAction("Get", "Student", new { id = form.Id });
		}
	}
}

Europe/Views/Student/Add.cshtml
@model Europe.Models.StudentForm

@{
    ViewBag.Title = "Add";
}

<h2>Créé ton profil</h2>
<hr />

@using (Html.BeginForm("Add", "Student", FormMethod.Post, new { @class = "formX" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.RoleType)
    @Html.HiddenFor(model => model.ImgId)

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pwd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pwd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pwd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPwd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPwd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPwd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Europe/Views/Student/Get.cshtml
@using Europe.Custom_Helpers;
@using Europe.Utils
@model Europe.Models.Student

@{
    ViewBag.Title = "Get";
}

<div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="img150"><img class="img-circle maxW90" src="@Url.Action("Get", "Img", new { id = Model.ImgId })" /></div>
        </div>
        <div class="col-md-3">
            <h2>@Html.DisplayFor(model => model.User.Name)</h2>
            <p>Points : @ViewBag.StudentPoint</p>

             @if (UserSession.User != null && UserSession.User.Id == Model.User.Id)
              {
                @Html.ActionLink("Editer le profil", "Update", "Student", new { id = Model.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink("Se déconnecter", "Disconnect", "Account", null, new { @class = "btn btn-default" })
              }
        </div>
    </div>
</div>

<hr />

<h3>Cours</h3>
<div class="container-fluid">
    <div id="studentCourses" class="row flex ">
        @if (UserSession.User != null && UserSession.User.Id == Model.User.Id)
        {
            if (Model.StudentCourses.Count() > 0)
            {
                foreach (var item in Model.StudentCourses)
                {
                    <div class="courseContainer row">
                        <div id="studentCoursesImg">
                            @Html.ImageActionLink(
                                string.Format("{0}", @Url.Action("Get", "Img", new { id = item.CourseImgId })), // imageUrl
                                "Learn", // actionName
                                "Course", // controller
                                new { courseId = item.CourseId }, // routeValues
                                new { @class = "img-circle maxW90" }, // htmlAttributes
                                string.Format("{0}", item.CourseTitle), // htmlAttributes
                                string.Format("{0}", item.CourseTitle), // htmlAttributes
                                null
                            )
                        </div>
                        <p>@Html.DisplayFor(modelItem => item.Points)</p>
                    </div>
                }
            }
            else
            {
                <p>Tu n'es inscrit à aucun cours, @Html.ActionLink("visite les cours disponibles", "Index", "Course")</p>
            }
        }
        else
        {
            if (Model.StudentCourses.Count() > 0)
            {
                foreach (var item in Model.StudentCourses)
                {
                    <div class="courseContainer row">
                        <div id="studentCoursesImg">
                            @Html.ImageActionLink(
                            string.Format("{0}", @Url.Action("Get", "Img", new { id = item.CourseImgId })), // imageUrl
                            "CourseDetails", // actionName
                            "Course", // controller
                            new { courseId = item.CourseId }, // routeValues
                            new { @class = "img-circle maxW90" }, // htmlAttributes
                            string.Format("{0}", item.CourseTitle), // htmlAttributes
                            string.Format("{0}", item.CourseTitle), // htmlAttributes
                            null
                        )
                        </div>
                        <p>@Html.DisplayFor(modelItem => item.Points)</p>
                    </div>
                }
            }
            else
            {
                <p>L'étudiant n'est inscrit à aucun cours ! Pour l'instant ...</p>
            }
        }
    </div>
</div>

<hr />

<h3>Certificats</h3>
<div id="studentCertificates">

</div>
<hr />

<h3>Badges</h3>
<div id="studentBadges">
    @foreach (var item in Model.StudentBadges)
    {
        @Html.DisplayFor(modelItem => item.Badge.Title)
        <div class="img150"><img class="img-circle maxW90" src="@Url.Action("Get", "Img", new { id = item.Badge.ImgId })" /></div>
        <p>Obtenu le @Html.DisplayFor(modelItem => item.Date)</p>
    }
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/jqueryunobtrusive")

Europe/Views/Student/Update.cshtml
@model Europe.Models.StudentUpdateForm

@{
    ViewBag.Title = "Update";
}

<h2>Modifie ton profil</h2>

@using (Html.BeginForm("Update", "Student", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div id="updateStudentForm" class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.ImgId)
    @Html.HiddenFor(model => model.UserId)

    <div id="avatarArea" class="img150">
        @Html.Action("DisplayImg", "Img", new { imgId = Model.ImgId })
        @Html.ActionLink("Supprimer l'avatar", "DeleteAvatar", "Img", new { imgId = Model.ImgId, userId = Model.UserId }, new { @class = "deleteAvatar" })
    </div>   

    <div class="form-group">
        <div id="changeAvatarArea">
            <input type="file" class="form-control-file" id="File" name="File" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div id="changePwdLink">
        @Html.CheckBoxFor(model => model.IsFlagSet)
        <label for="IsFlagSet">Modifier le mot de passe</label>
    </div>

    <div id="pwdFormContainer">
        <div class="form-group">
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.CurrentPwd, htmlAttributes: new { placeholder = "Ton mot de passe actuel", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CurrentPwd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NewPwd, htmlAttributes: new { placeholder = "Ton nouveau mot de passe", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NewPwd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ConfirmPwd, htmlAttributes: new { placeholder = "Confirme ton nouveau mot de passe", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ConfirmPwd, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Valider" class="btn btn-default" />
        </div>
    </div>
</div>
}
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/jqueryunobtrusive")

<script>

    // Sauvegarde du HTML de la vue partielle chargée d'affichier l'avatar via Html.Action("DisplayImg")
    const partialAvatarArea = $("#avatarArea").html();

    $(document).ready(function () {

        // Input type File
        // Quand l'utilisateur upload une image, on lit le fichier et on ajoute un bouton annuler

        $("#File").change(function () {
            var File = this.files;
            if (File && File[0]) {
                ReadImage(File[0]);
            }
            if ($("#resetAvatar").length) {
                // on ne fait rien
            }
            else
            {
                $("#avatarArea").append('<a href="#" onclick="ClearPreview()" id="resetAvatar">Annuler</a>');
            }
        })

        // Html.ActionLink("DeleteAvatar) Ajaxify
        // Quand l'utilisateur souhaite supprimer son avatar et revenir à l'avatar par défaut
        $(".deleteAvatar").click(function () {
            if (confirm('Are you sure?')) {
                if ($("#ImgId").val() == 2) {
                    alert("on ne peut pas supprimer l'avatar par défaut");
                }
                else
                {
                    $.ajax({
                        url: this.href,
                        type: 'POST',
                        context: this,
                        success: function (result) {
                            //$(this).closest('div').remove();
                            $('#avatar').attr('src', 'Get/Img/' + result.Id);
                            $('#avatar').attr('alt', result.Alt);
                            alert('ça marche')
                        }
                    });
                }
            }
            return false;
        })

    })

    // Input type File
    // Fonction pour lire le fichier

    var ReadImage = function (file) {

        // Création d'un reader et d'une image
        var reader = new FileReader;
        var image = new Image;

        reader.readAsDataURL(file);

        // Au chargement on récupère l'image chargée pour l'insérer en mode preview et on supprime les anciens attributs 

        reader.onload = function (_file) {
            image.src = _file.target.result;
            image.onload = function () {
                $("#avatarArea").empty();
                $('#avatarArea').append('<img id="avatar"/>');
                $("#avatar").attr('src', _file.target.result);
                $("#avatarArea").append('<a href="#" onclick="ClearPreview()" id="resetAvatar">Annuler</a>');
            }
        }
    }

    // Input type File
    // On remet les informations de l'ancienne image si le user annule 
    var ClearPreview = function (e) {
        event.preventDefault();
        $("#avatarArea").empty();
        $("#avatarArea").html(partialAvatarArea);
        $("#File").val('');
    };
</script>

Europe/Views/Student/Update2.cshtml
@model Europe.Models.Student.StudentUpdateForm

@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>

@using (Html.BeginForm("Update", "Student", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>StudentUpdateForm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.ImgId)

        <div class="removeImage">Supprimer l'avatar</div>

        @Html.TextBoxFor(model => Model.File, new { type = "file" })
        @Html.ValidationMessageFor(model => Model.File)

        <div class="form-group">
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="changePwdLink">
            @Html.CheckBoxFor(model => model.IsFlagSet)
            <label for="IsFlagSet">Modifier le mot de passe</label>
        </div>

        <div id="pwdFormContainer">
            <div class="form-group">
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.CurrentPwd, htmlAttributes: new { placeholder = "Ton mot de passe actuel", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CurrentPwd, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.NewPwd, htmlAttributes: new { placeholder = "Ton nouveau mot de passe", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NewPwd, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.ConfirmPwd, htmlAttributes: new { placeholder = "Confirme ton nouveau mot de passe", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ConfirmPwd, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div id="changePwdBody"></div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<!-- For unobtrusive-ajax && For validate and validate-unobtrusive -->
@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryunobtrusive")
    @Scripts.Render("~/bundles/Custom")

}